apiVersion: apps/v1
kind: Deployment
metadata:
  name: zis-frontend
spec:
  selector:
    matchLabels:
      app: zis-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: zis-frontend
    spec:
      containers:
        - name: zis-frontend
          imagePullPolicy: Always
          image: iyansr/zis-frontend
          ports:
            - containerPort: 3000
